/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
/////////////////////////////////////////
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using FlexUI;

namespace Sample
{
    public partial class SampleScript2 : FlexUI.BaseView //Autogenerated
    {
        public static SampleScript2 Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Button = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Button1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextTMP = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Button);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(Button1);
            SubscribeOnChanged(TextTMP);
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        #endregion
    }
}