/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
/////////////////////////////////////////
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using FlexUI;

namespace SSS
{
    public partial class Sample11 : FlexUI.BaseView //Autogenerated
    {
        public static Sample11 Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Button = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Toggle Toggle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Checkmark = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Label = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Button);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(Toggle);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(Checkmark);
            SubscribeOnChanged(Label);
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        #endregion
    }
}