using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using FlexUI;
using UnityEngine.Serialization;

namespace Sample
{
    public class Sample1 : BaseView
    {
        [SerializeField]
        private Button buttonA;
#region Autogenerated
        //////////////////////////////////////////////////////////////////////////////////
        // === THIS IS AUTOGENERATED CODE ===  //
        // === DO NOT CHANGE MANUALLY ===  //
#pragma warning disable 0414
#if UNITY_EDITOR
        /// <summary>
        /// Used as mark for Editor.
        /// </summary>
        [HideInInspector] public bool IsBuilt = true;
#endif
        public static Sample1 Instance { get; private set; }
        
        // Controls
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ButtonRed = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ButtonYellow = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextTMP = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ButtonGreen = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextTMP1 = default;
        [FormerlySerializedAs("SampleScript2")]
        [AutoGenerated, SerializeField] protected Sample.Sample2 Sample2 = default;
        [AutoGenerated, SerializeField] protected Sample.Sample3 Sample3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ButtonError = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextTMP2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ButtonMessage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextTMP3 = default;
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ButtonRed);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(ButtonYellow);
            SubscribeOnChanged(TextTMP);
            SubscribeOnChanged(ButtonGreen);
            SubscribeOnChanged(TextTMP1);
            SubscribeOnChanged(Sample2);
            SubscribeOnChanged(Sample3);
            SubscribeOnChanged(ButtonError);
            SubscribeOnChanged(TextTMP2);
            SubscribeOnChanged(ButtonMessage);
            SubscribeOnChanged(TextTMP3);
        }
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
#pragma warning restore 0414
        // === End of AUTOGENERATED CODE ===  //
        //////////////////////////////////////////////////////////////////////////////////
#endregion
    }
}