using FlexUI;
using UnityEngine;

namespace Sample
{
    public class Sample2 : BaseView
    {
        protected override void OnHidden()
        {
            Debug.Log($"{GetType().Name} is closed");
        }

#region Autogenerated
        //////////////////////////////////////////////////////////////////////////////////
        // === THIS IS AUTOGENERATED CODE ===  //
        // === DO NOT CHANGE MANUALLY ===  //
#pragma warning disable 0414
#if UNITY_EDITOR
        /// <summary>
        /// Used as mark for Editor.
        /// </summary>
        [HideInInspector] public bool IsBuilt = true;
#endif
        public static Sample2 Instance { get; private set; }

        // Controls
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Button = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Text = default;

        protected override void AutoInit()
        {
            Instance = this;
        }

        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Button);
            SubscribeOnChanged(Text);
        }

        public static void ShowInstance() => Instance.Show();

        public static void HideInstance() => Instance.Hide();
#pragma warning restore 0414
        // === End of AUTOGENERATED CODE ===  //
        //////////////////////////////////////////////////////////////////////////////////
#endregion
    }
}
